
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Green-leaf-coffee/springcloud-config.git
          search-paths:
#            探索路径
            - springcloud-config
#     探索分支
      label: master
  application:
    name: test

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone:  http://localhost7002:7002/eureka, http://localhost7001:7001/eureka

server:
  port: 3344
